"""UNSAT-recall LaTeX table — percentage-only (compact) variant.

Identical data to ``main_table_recall.py`` but each cell is just the
recall percentage, dropping the ``(correct/total)`` breakdown line so
the table fits in tighter columns. Use the regular
``main_table_recall.tex`` if you want the V/total numerator/denominator
visible; use this one when space is the constraint.

Usage::

    python -m examples.FlowConformal.paper.tables.main_table_recall_compact
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _common import write_table  # noqa: E402

from main_table import (  # noqa: E402
    BENCHMARKS,
    BENCHMARK_HEADER,
    DEFAULT_EXP1,
    DEFAULT_EXP2,
    DEFAULT_VNNCOMP,
    METHOD_ROWS,
    REPO,
)

from main_table_recall import (  # noqa: E402
    BOLD_CELLS,
    NA_CELL,
    _effective_gt,
    cell_metrics,
)


def fmt_cell_compact(metrics: Optional[dict], bold: bool = False) -> str:
    """Percentage-only cell. Daggers preserved, no V/total breakdown."""
    if metrics is None:
        return NA_CELL
    correct = metrics["correct_unsat"]
    total = metrics["total_gt_unsat"]
    sound = metrics.get("n_sound", 0)
    if total == 0:
        return NA_CELL
    pct = 100.0 * correct / total
    pct_num = f"{pct:.1f}\\%"
    if bold:
        pct_num = r"\textbf{" + pct_num + "}"
    if sound > 0:
        pct_num += r"\textsuperscript{$\dagger$" + str(sound) + "}"
    return pct_num


def build_table_compact(
    exp1_dir: Path, exp2_dir: Path, vnncomp_dir: Path,
    effective_gt: dict, gt_unsat_total: dict,
) -> str:
    L: list[str] = []
    L.append(
        r"% Auto-generated by examples/FlowConformal/paper/tables/"
        r"main_table_recall_compact.py"
    )
    L.append(r"% Required LaTeX packages: booktabs, makecell.")
    L.append(r"\begin{table*}[!t]")
    L.append(r"\centering")
    L.append(
        r"\caption{UNSAT-recall on VNN-COMP'25 benchmarks (compact). "
        r"Each cell reports \emph{UNSAT-recall}\,$\uparrow$ = "
        r"$\#\,\mathrm{correct}\,\mathrm{UNSAT} / "
        r"\#\,\mathrm{effective}\,\mathrm{UNSAT}$. An instance counts "
        r"as \emph{effective UNSAT} if the VNN-COMP'25 ground-truth "
        r"consensus is UNSAT or if every sound tool timed out / "
        r"abstained \emph{and} no tool emitted a SAT counterexample. "
        r"This denominator is the same across methods. The numerator "
        r"counts instances where the tool emitted UNSAT and the "
        r"effective ground truth is UNSAT (sound violations excluded "
        r"from the numerator). A dagger ($\dagger N$) annotates cells "
        r"where the tool committed $N$ sound violations\,---\,$N$ "
        r"matches the dagger count in the companion \% Solved table. "
        r"An em-dash ($-$) indicates the verifier's loader does not "
        r"support the network, the benchmark was not run, or the "
        r"benchmark has no effective-UNSAT instances. \textbf{Bold} "
        r"percentages indicate per-column highlights. Companion table "
        r"\ref{tab:main_results_recall} reports the same data with the "
        r"$(\#\,\mathrm{correct} / \#\,\mathrm{total})$ breakdown.}"
    )
    L.append(r"\label{tab:main_results_recall_compact}")
    L.append(r"\setlength{\tabcolsep}{4pt}")
    L.append(r"\renewcommand{\arraystretch}{1.05}")
    L.append(r"\footnotesize")
    L.append(r"\begin{tabular}{l ccccccccc}")
    L.append(r"\toprule")

    header_cells = [r"\textbf{Method}"]
    for b in BENCHMARKS:
        top, bot = BENCHMARK_HEADER[b]
        header_cells.append(r"\makecell{" + top + r"\\" + bot + "}")
    L.append(" & ".join(header_cells) + r" \\")
    L.append(r"\midrule")

    n_cols = 1 + len(BENCHMARKS)

    last_group = None
    for method_id, display_name, group in METHOD_ROWS:
        if last_group is not None and group != last_group:
            L.append(r"\midrule[\heavyrulewidth]")
            if group == "sound":
                L.append(r"\multicolumn{" + str(n_cols)
                         + r"}{l}{\textit{Sound verifiers (from VNN-COMP'25)}} \\")
                L.append(r"\cmidrule(lr){1-" + str(n_cols) + "}")
            elif group == "prob":
                L.append(r"\multicolumn{" + str(n_cols)
                         + r"}{l}{\textit{Probabilistic verifiers}} \\")
                L.append(r"\cmidrule(lr){1-" + str(n_cols) + "}")

        cells = [display_name]
        for bench in BENCHMARKS:
            metrics = cell_metrics(
                method_id, bench, effective_gt, gt_unsat_total,
                exp1_dir, exp2_dir, vnncomp_dir,
            )
            cells.append(
                fmt_cell_compact(metrics,
                                 bold=(method_id, bench) in BOLD_CELLS)
            )
        L.append(" & ".join(cells) + r" \\")
        last_group = group

    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table*}")
    return "\n".join(L) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exp1-csv-dir", type=Path, default=DEFAULT_EXP1)
    parser.add_argument("--exp2-csv-dir", type=Path, default=DEFAULT_EXP2)
    parser.add_argument("--vnncomp-dir", type=Path, default=DEFAULT_VNNCOMP)
    parser.add_argument(
        "--output", type=Path,
        default=Path(__file__).resolve().parent
        / "outputs" / "main_table_recall_compact.tex",
    )
    args = parser.parse_args()

    effective_gt, gt_unsat_total = _effective_gt(REPO)
    table_tex = build_table_compact(
        args.exp1_csv_dir, args.exp2_csv_dir, args.vnncomp_dir,
        effective_gt, gt_unsat_total,
    )
    write_table(args.output, table_tex)
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
