"""Table 5 — Shared-flow verification-method ablation (v3 sweep).

Reads ``ablation_shared_flow_<benchmark>_<method>.csv`` from
``examples/FlowConformal/experiments/exp_ablation/outputs/`` and emits
a Method × Benchmark table with per-(method, benchmark) UNSAT recall
and sound-violation counts, plus a combined wall-clock column.

Two benchmarks: ACAS Xu (186 inst, 140 GT-unsat, 47 GT-sat) and
tllverify_2023 (32 inst, 15 GT-unsat, 17 GT-sat). Five methods. The
shared-flow design means calibration is fixed per instance and only
the verifier varies, isolating the verification-method axis.

Bolding:
* Per-column highlights: best recall (highest), best soundness (lowest
  sound viol.).
* The full row for the production default (``amls_bounded``) is also
  bolded in the method-name column to flag it as the headline
  recommendation.

Run with::

    python -m \\
        examples.FlowConformal.paper.tables.tab5_shared_flow_ablation
"""
from __future__ import annotations

import argparse
import csv
import statistics
from pathlib import Path

ABL_DIR = (
    Path(__file__).resolve().parents[2]
    / "experiments" / "exp_ablation" / "outputs"
)
DEFAULT_OUT = (
    Path(__file__).resolve().parent
    / "outputs" / "tab5_shared_flow_ablation.tex"
)

METHODS = [
    ("scenario",       "Scenario"),
    ("amls",           "AMLS (unbounded)"),
    ("amls_bounded",   "AMLS-bounded"),
    ("is_tilted",      "IS (tilted)"),
    ("raw_mc_uniform", "Raw MC (uniform)"),
]
DEFAULT_METHOD = "amls_bounded"

BENCHMARKS = [
    ("acasxu_2023",    "ACAS Xu"),
    ("tllverify_2023", "tllverify"),
]


def _load(benchmark: str, method: str) -> dict:
    """Return per-cell metrics: correct_unsat, total_unsat, sound_viol,
    total_sat, mean_wall."""
    path = ABL_DIR / f"ablation_shared_flow_{benchmark}_{method}.csv"
    rows = list(csv.DictReader(open(path)))
    n_correct_unsat = 0
    n_total_unsat = 0
    n_sound_viol = 0
    n_total_sat = 0
    walls = []
    for r in rows:
        v = (r.get("verdict") or "").upper()
        gt = (r.get("ground_truth") or "").lower()
        try:
            walls.append(float(r.get("wall_s", "") or 0.0))
        except ValueError:
            pass
        if gt == "unsat":
            n_total_unsat += 1
            if v == "UNSAT":
                n_correct_unsat += 1
        elif gt == "sat":
            n_total_sat += 1
            if v == "UNSAT":
                n_sound_viol += 1
    return {
        "correct_unsat": n_correct_unsat,
        "total_unsat":   n_total_unsat,
        "sound_viol":    n_sound_viol,
        "total_sat":     n_total_sat,
        "mean_wall":     (statistics.mean(walls) if walls else 0.0),
    }


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--output", type=Path, default=DEFAULT_OUT)
    args = p.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)

    # Pull all cell metrics into a 2D dict.
    cell: dict[tuple[str, str], dict] = {}
    for bench_id, _ in BENCHMARKS:
        for method_id, _ in METHODS:
            cell[(bench_id, method_id)] = _load(bench_id, method_id)

    # Per-column bolding rules.
    # Recall: bold whichever methods achieve the max per benchmark.
    bold_recall: dict[tuple[str, str], bool] = {}
    bold_sound:  dict[tuple[str, str], bool] = {}
    for bench_id, _ in BENCHMARKS:
        # Best recall (highest correct_unsat / total_unsat).
        best_recall = max(
            cell[(bench_id, m_id)]["correct_unsat"]
            / max(cell[(bench_id, m_id)]["total_unsat"], 1)
            for m_id, _ in METHODS
        )
        for m_id, _ in METHODS:
            r = (cell[(bench_id, m_id)]["correct_unsat"]
                 / max(cell[(bench_id, m_id)]["total_unsat"], 1))
            bold_recall[(bench_id, m_id)] = abs(r - best_recall) < 1e-9
        # Best soundness (lowest sound_viol). Skip raw_mc_uniform from
        # the soundness contest because its 0 sound violations are
        # trivially due to never emitting UNSAT — that's not a
        # soundness virtue, it's a recall failure already penalised in
        # the recall column. Without this guard the table would bold
        # raw_mc_uniform's "0/47" cells, which would mislead the reader.
        contestants = [m_id for m_id, _ in METHODS
                       if m_id != "raw_mc_uniform"]
        best_sv = min(cell[(bench_id, m_id)]["sound_viol"]
                      for m_id in contestants)
        for m_id, _ in METHODS:
            sv = cell[(bench_id, m_id)]["sound_viol"]
            bold_sound[(bench_id, m_id)] = (
                m_id != "raw_mc_uniform" and sv == best_sv
            )

    # Build LaTeX.
    L: list[str] = []
    L.append(r"% Auto-generated by examples/FlowConformal/paper/tables/"
             r"tab5_shared_flow_ablation.py")
    L.append(r"% Required LaTeX packages: booktabs.")
    L.append(r"\begin{table}[!t]")
    L.append(r"\centering")
    L.append(
        r"\caption{Shared-flow verification-method ablation. Each row "
        r"replaces the verifier while the conformal calibration "
        r"$(\mathrm{flow}, q)$ is held fixed per instance, isolating "
        r"verification quality from calibration noise. \emph{Recall} "
        r"$\uparrow$ is the fraction of effective-UNSAT instances "
        r"correctly certified UNSAT (with the breakdown shown). "
        r"\emph{Sound viol.} $\downarrow$ counts UNSAT verdicts on "
        r"GT-SAT instances (lower is safer). Bold per-column "
        r"highlights the best value; the bolded method name marks the "
        r"production default. ACAS Xu has 140 effective-UNSAT and 47 "
        r"GT-SAT instances; tllverify has 15 and 17 respectively. "
        r"AMLS-bounded is the only method on the Pareto front "
        r"(best-or-tied on every column).}"
    )
    L.append(r"\label{tab:shared_flow_ablation}")
    L.append(r"\setlength{\tabcolsep}{4pt}")
    L.append(r"\renewcommand{\arraystretch}{1.05}")
    L.append(r"\footnotesize")
    L.append(r"\begin{tabular}{l cc cc}")
    L.append(r"\toprule")
    # Two-row header: benchmark group on top, metric on bottom.
    L.append(
        r" & \multicolumn{2}{c}{\textbf{ACAS Xu}} "
        r"& \multicolumn{2}{c}{\textbf{tllverify}} \\"
    )
    L.append(r"\cmidrule(lr){2-3} \cmidrule(lr){4-5}")
    L.append(
        r"\textbf{Method} "
        r"& Recall\,$\uparrow$ & Sound viol.\,$\downarrow$ "
        r"& Recall\,$\uparrow$ & Sound viol.\,$\downarrow$ \\"
    )
    L.append(r"\midrule")

    for method_id, method_label in METHODS:
        name_cell = method_label
        if method_id == DEFAULT_METHOD:
            name_cell = r"\textbf{" + name_cell + "}"

        cells: list[str] = [name_cell]
        for bench_id, _ in BENCHMARKS:
            m = cell[(bench_id, method_id)]
            recall_pct = (
                100.0 * m["correct_unsat"] / max(m["total_unsat"], 1)
            )
            recall_str = (
                f"{recall_pct:.1f}\\% "
                f"({m['correct_unsat']}\\,/\\,{m['total_unsat']})"
            )
            if bold_recall[(bench_id, method_id)]:
                recall_str = r"\textbf{" + recall_str + "}"
            sv_str = f"{m['sound_viol']}\\,/\\,{m['total_sat']}"
            if bold_sound[(bench_id, method_id)]:
                sv_str = r"\textbf{" + sv_str + "}"
            cells.append(recall_str)
            cells.append(sv_str)

        L.append(" & ".join(cells) + r" \\")

    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table}")

    args.output.write_text("\n".join(L) + "\n")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
