"""Per-cell empirical false-UNSAT rate vs. the joint-bound budget.

For each (method, benchmark) cell where the method can emit an UNSAT
verdict (i.e., is a probabilistic or sound verifier), this script
computes::

    n_false_unsat = #(verdict == UNSAT AND ground_truth == sat)
    n_decided_unsat = #(verdict == UNSAT)
    rate = n_false_unsat / n_decided_unsat

The theoretical per-instance bound from Theorem 1 is ``epsilon + eta
~= 1.1e-3`` and holds with confidence ``delta_2 (1 - delta_3) ~= 0.947``,
so the per-instance bound on the false-UNSAT event is roughly
``1 - 0.947 = 0.053`` (the bound holds for 94.7% of calibration draws,
and on the bound-holds event the unsafe-mass is at most 1.1e-3, so any
single decided-UNSAT instance has false-UNSAT probability at most
0.053 in the worst case).

Reuses CSV-loading conventions from ``main_table.py``.

Usage::

    python -m examples.FlowConformal.paper.tables.tab_empirical_violation \\
        --output /path/to/paper/tables/tab_empirical_violation.tex
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path
from typing import Optional

csv.field_size_limit(sys.maxsize)
sys.path.insert(0, str(Path(__file__).resolve().parent))

from main_table import (  # noqa: E402
    BENCHMARKS,
    BENCHMARK_HEADER,
    DEFAULT_EXP1,
    DEFAULT_EXP2,
    DEFAULT_VNNCOMP,
    REPO,
    SOUND_VERIFIERS,
    _read_internal_csv,
    _read_vnncomp_csv,
    csv_path,
    load_ground_truth,
)
from _common import write_table  # noqa: E402


# Methods to report. Sound verifiers excluded since their false-UNSATs
# (if any) are sound-soundness violations of the verifier and not the
# subject of the joint bound.
METHOD_ROWS: list[tuple[str, str]] = [
    ("ours", r"\textbf{Ours}"),
    ("hashemi_clipping", r"CLIP\,"),
    ("saver", "SaVer"),
]


NA_CELL = r"\multicolumn{1}{c}{$-$}"


def cell_metrics(method: str, bench: str, gt: dict[tuple[str, str, str], str],
                 exp1_dir: Path, exp2_dir: Path, vnncomp_dir: Path
                 ) -> Optional[dict]:
    path = csv_path(method, bench, exp1_dir, exp2_dir, vnncomp_dir)
    if path is None:
        return None
    if method in SOUND_VERIFIERS:
        rows = _read_vnncomp_csv(path)
    else:
        rows = _read_internal_csv(path)
    if not rows:
        return None
    INAPPLICABLE = {"ERROR", "NOT_APPLICABLE", "SKIPPED"}
    if all(r["verdict"] in INAPPLICABLE for r in rows):
        return None

    n_decided_unsat = 0
    n_false_unsat = 0
    for r in rows:
        if r["verdict"] != "UNSAT":
            continue
        n_decided_unsat += 1
        g = gt.get((bench, r["onnx_file"], r["vnnlib_file"]), "")
        if g == "sat":
            n_false_unsat += 1
    return {
        "n_decided_unsat": n_decided_unsat,
        "n_false_unsat": n_false_unsat,
    }


def fmt_cell(metrics: Optional[dict]) -> str:
    if metrics is None:
        return NA_CELL
    n = metrics["n_decided_unsat"]
    k = metrics["n_false_unsat"]
    if n == 0:
        return r"\makecell{$-$\\(0/0)}"
    rate = 100.0 * k / n
    rate_str = f"{rate:.2f}\\%"
    return r"\makecell{" + rate_str + r"\\(" + str(k) + r"\,/\," + str(n) + ")}"


def build_table(exp1_dir: Path, exp2_dir: Path, vnncomp_dir: Path,
                gt: dict[tuple[str, str, str], str]) -> str:
    L: list[str] = []
    L.append(r"% Auto-generated by examples/FlowConformal/paper/tables/tab_empirical_violation.py")
    L.append(r"% Required LaTeX packages: booktabs, makecell.")
    L.append(r"\begin{table*}[!t]")
    L.append(r"\centering")
    L.append(
        r"\caption{Empirical false-UNSAT rate per (method, benchmark) cell. Each "
        r"cell reports the rate over the breakdown $(\#\,\mathrm{false\,UNSAT}\,/\,"
        r"\#\,\mathrm{UNSAT\,verdicts})$. A false UNSAT is an UNSAT verdict on an "
        r"instance whose VNN-COMP'25 ground-truth consensus is SAT. For our "
        r"pipeline at $\epsilon = 10^{-3}$, $\eta = 10^{-4}$, the joint bound "
        r"says $\Pr_{x \sim \mathcal{W}}[f(x) \in \mathbf{U}] \le 1.1 \times 10^{-3}$ "
        r"per decided-UNSAT instance with confidence $\delta_2(1 - \delta_3) \approx "
        r"0.947$, so the per-instance false-UNSAT probability is at most $1 - 0.947 "
        r"= 0.053$ in the worst case.}"
    )
    L.append(r"\label{tab:empirical_violation}")
    L.append(r"\setlength{\tabcolsep}{3pt}")
    L.append(r"\renewcommand{\arraystretch}{1.05}")
    L.append(r"\footnotesize")
    L.append(r"\begin{tabular}{l ccccccccc}")
    L.append(r"\toprule")

    header_cells = [r"\textbf{Method}"]
    for b in BENCHMARKS:
        top, bot = BENCHMARK_HEADER[b]
        header_cells.append(r"\makecell{" + top + r"\\" + bot + "}")
    L.append(" & ".join(header_cells) + r" \\")
    L.append(r"\midrule")

    for method_id, display_name in METHOD_ROWS:
        cells = [display_name]
        for bench in BENCHMARKS:
            metrics = cell_metrics(
                method_id, bench, gt, exp1_dir, exp2_dir, vnncomp_dir,
            )
            cells.append(fmt_cell(metrics))
        L.append(" & ".join(cells) + r" \\")

    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table*}")
    return "\n".join(L) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exp1-csv-dir", type=Path, default=DEFAULT_EXP1)
    parser.add_argument("--exp2-csv-dir", type=Path, default=DEFAULT_EXP2)
    parser.add_argument("--vnncomp-dir", type=Path, default=DEFAULT_VNNCOMP)
    parser.add_argument(
        "--output", type=Path,
        default=Path(__file__).resolve().parent / "outputs" / "tab_empirical_violation.tex",
    )
    args = parser.parse_args()

    gt = load_ground_truth(REPO)
    table_tex = build_table(
        args.exp1_csv_dir, args.exp2_csv_dir, args.vnncomp_dir, gt,
    )
    write_table(args.output, table_tex)
    print(f"Wrote {args.output}")
    print()
    print("Per-(method, benchmark) summary:")
    for method_id, display_name in METHOD_ROWS:
        for bench in BENCHMARKS:
            m = cell_metrics(method_id, bench, gt,
                             args.exp1_csv_dir, args.exp2_csv_dir, args.vnncomp_dir)
            if m is None:
                continue
            n = m["n_decided_unsat"]
            k = m["n_false_unsat"]
            rate = 100.0 * k / n if n > 0 else 0.0
            print(f"  {method_id:24s} {bench:24s} {k:3d}/{n:4d} ({rate:.2f}%)")


if __name__ == "__main__":
    main()
