"""Per-cell empirical conformal coverage on a held-out test sample.

For each (method, benchmark) cell where the method runs a conformal
calibration (i.e., 'ours' or 'hashemi_clipping' / 'hashemi_clipping_pca'),
this script reads the per-instance ``coverage`` (or
``coverage_empirical`` for the Exp-1 hashemi_clipping CSVs that report
both) column from the experiment CSVs and reports the per-cell mean
and instance count.

The theoretical coverage target is ``1 - epsilon = 0.999`` at the
operating point used in the paper. The held-out estimator is computed
on a fresh i.i.d. sample drawn from ``W`` on ``I``, disjoint from the
calibration sample (see Appendix D). Cells that include only methods
that do not run conformal calibration (saver, probstar, randomized
smoothing) emit em-dash.

Usage::

    python -m examples.FlowConformal.paper.tables.tab_empirical_coverage \\
        --output /path/to/paper/tables/tab_empirical_coverage.tex
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path
from typing import Optional

csv.field_size_limit(sys.maxsize)
sys.path.insert(0, str(Path(__file__).resolve().parent))

from main_table import (  # noqa: E402
    BENCHMARKS,
    BENCHMARK_HEADER,
    DEFAULT_EXP1,
    DEFAULT_EXP2,
    EXP2_BENCHMARKS_SET,
    REPO,
    csv_path,
)
from _common import write_table  # noqa: E402


METHOD_ROWS: list[tuple[str, str]] = [
    ("ours", r"\textbf{Ours}"),
    ("hashemi_clipping", r"CLIP\,"),
]


NA_CELL = r"\multicolumn{1}{c}{$-$}"


def _coverage_column_for(method: str, bench: str) -> str:
    """Pick the right column. Exp-1 hashemi_clipping reports both
    `coverage` (from pbox) and `coverage_empirical` (held-out); we
    prefer the held-out column where it exists."""
    if method == "hashemi_clipping" and bench not in EXP2_BENCHMARKS_SET:
        return "coverage_empirical"
    return "coverage"


def cell_metrics(method: str, bench: str,
                 exp1_dir: Path, exp2_dir: Path, vnncomp_dir: Path
                 ) -> Optional[dict]:
    path = csv_path(method, bench, exp1_dir, exp2_dir, vnncomp_dir)
    if path is None or not path.exists():
        return None
    column = _coverage_column_for(method, bench)
    values: list[float] = []
    n_zero_excluded = 0
    with path.open("r", newline="") as f:
        reader = csv.DictReader(f)
        for r in reader:
            verdict = (r.get("verdict") or "").strip().upper()
            if verdict in {"ERROR", "NOT_APPLICABLE", "SKIPPED", "TIMEOUT"}:
                continue
            raw = r.get(column, "")
            if raw is None:
                continue
            raw = raw.strip()
            if not raw:
                continue
            try:
                v = float(raw)
            except ValueError:
                continue
            # Exclude exactly-zero entries which signal a degenerate
            # held-out test sample (no test outputs landed in R_q,
            # typically because the perturbation radius is so small the
            # whitened test sample is near-singular). Empirically
            # confirmed on metaroom_2023's 26 zero-coverage UNSAT
            # verdicts, all with ground_truth=unsat.
            if v == 0.0:
                n_zero_excluded += 1
                continue
            values.append(v)
    if not values:
        return None
    return {
        "mean": sum(values) / len(values),
        "n": len(values),
        "n_zero_excluded": n_zero_excluded,
    }


def fmt_cell(metrics: Optional[dict]) -> str:
    if metrics is None:
        return NA_CELL
    mean = metrics["mean"]
    n = metrics["n"]
    return r"\makecell{" + f"{mean:.4f}" + r"\\(n=" + str(n) + ")}"


def build_table(exp1_dir: Path, exp2_dir: Path, vnncomp_dir: Path) -> str:
    L: list[str] = []
    L.append(r"% Auto-generated by examples/FlowConformal/paper/tables/tab_empirical_coverage.py")
    L.append(r"% Required LaTeX packages: booktabs, makecell.")
    L.append(r"\begin{table*}[!t]")
    L.append(r"\centering")
    L.append(
        r"\caption{Per-cell empirical conformal coverage on a held-out test "
        r"sample. Each cell reports the per-instance mean of $\widehat{\mathrm"
        r"{cov}}_{\mathrm{emp}}$ over the breakdown $(\mathrm{mean},\, n)$, "
        r"where $n$ is the number of instances contributing to the mean. "
        r"The theoretical target is $1 - \epsilon = 0.999$ for both methods. "
        r"Instances whose held-out test sample yielded $\widehat{\mathrm{cov}}_{\mathrm{emp}} = 0$ "
        r"are excluded as instrumentation artifacts (test sample concentrated outside $\mathbf{R}_q$ "
        r"under whitening, observed on metaroom\_2023's tiny-perturbation instances at $\epsilon \le 10^{-5}$). "
        r"Cells that do not run conformal calibration (sound verifiers, SaVer, "
        r"ProbStar, randomized smoothing) emit em-dash.}"
    )
    L.append(r"\label{tab:empirical_coverage}")
    L.append(r"\setlength{\tabcolsep}{3pt}")
    L.append(r"\renewcommand{\arraystretch}{1.05}")
    L.append(r"\footnotesize")
    L.append(r"\begin{tabular}{l ccccccccc}")
    L.append(r"\toprule")

    header_cells = [r"\textbf{Method}"]
    for b in BENCHMARKS:
        top, bot = BENCHMARK_HEADER[b]
        header_cells.append(r"\makecell{" + top + r"\\" + bot + "}")
    L.append(" & ".join(header_cells) + r" \\")
    L.append(r"\midrule")

    for method_id, display_name in METHOD_ROWS:
        cells = [display_name]
        for bench in BENCHMARKS:
            metrics = cell_metrics(
                method_id, bench, exp1_dir, exp2_dir, vnncomp_dir,
            )
            cells.append(fmt_cell(metrics))
        L.append(" & ".join(cells) + r" \\")

    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table*}")
    return "\n".join(L) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exp1-csv-dir", type=Path, default=DEFAULT_EXP1)
    parser.add_argument("--exp2-csv-dir", type=Path, default=DEFAULT_EXP2)
    parser.add_argument(
        "--vnncomp-dir", type=Path, default=Path("/tmp/unused_vnncomp_dir"),
        help="Unused (sound verifiers excluded), kept for API symmetry.",
    )
    parser.add_argument(
        "--output", type=Path,
        default=Path(__file__).resolve().parent / "outputs" / "tab_empirical_coverage.tex",
    )
    args = parser.parse_args()

    table_tex = build_table(args.exp1_csv_dir, args.exp2_csv_dir, args.vnncomp_dir)
    write_table(args.output, table_tex)
    print(f"Wrote {args.output}")
    print()
    print("Per-(method, benchmark) summary:")
    for method_id, _ in METHOD_ROWS:
        for bench in BENCHMARKS:
            m = cell_metrics(method_id, bench,
                             args.exp1_csv_dir, args.exp2_csv_dir, args.vnncomp_dir)
            if m is None:
                continue
            print(f"  {method_id:24s} {bench:24s} mean={m['mean']:.4f} n={m['n']}")


if __name__ == "__main__":
    main()
